yast2: avoid overlap between original and restructured trees
The overlap would cause problems like:

  * Compiling src/modules/modules/Crash.ycp...
    ERROR: Compiling src/modules/modules/Crash.ycp failed.

(which I mistakenly attributed to threading)
or

  fatal: cannot move directory over file, source=library/modules, destination=src/modules/modules

Therefore moving the original library/modules (which was in the
meantime src/modules) to library/general/src/modules.